---
- name: mariarpm
  package: name={{ item }} state=installed
  with_items:
    - mariadb
    - mariadb-client
    - mariadb-tools
    - python-mysql

- name: create my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf

- name: start_mariadb
  service: name={{ mariadb_service }} state=started enabled=yes


- name: Create a new database with name '{{ mariadb }}'
  mysql_db:
    name: "{{ mariadb }}"
    state: present


